### ISSUE TITLE
No matching function for call

### ISSUE THREAD

**Issue by prabhat0987** [benzi96/snort3-plugin-ML#2]
Hey,
When I make snort3_extra with this plugin, it shows these errors - 
In line 184 of plugin/packet_generated.h
`error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)  verifier.Verify(protocol_type())`  

In line 186 of plugin/packet_generated.h
`error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)  verifier.Verify(service())`

In line 188 of plugin/packet_generated.h
`error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)  verifier.Verify(flag())`

**Comment by benzi96** [comment]
https://github.com/google/flatbuffers
install flatbuffer for create packet.py packet_generated.h

git clone https://github.com/google/flatbuffers.git
cd flatbuffers
cmake -G "Unix Makefiles"
make
./flattests

**Comment by odin-codin-brain** [comment]
This work seems interesting. Can you please post/reply the procedure of how to implement alongside SNORT?

**Comment by Crimrose** [comment]
> This work seems interesting. Can you please post/reply the procedure of how to implement alongside SNORT?

Hello,
I have uploaded docs how to setup this plugin belong with snort3. You can check at [docs folder](https://github.com/benzi96/snort3-plugin-ML/tree/master/docs). It's written in Vietnamese, but I think you can use google translate to read it.

**Comment by odin-codin-brain** [comment]
Thanks.

**Comment by ahuseinnf** [comment]
hello i got this error

/snort_src/snort3_extra-master/src/inspectors/dpx/packet_generated.h:182:54: error: no matching function for call to ‘kmeans::Packet::VerifyField<int32_t>(flatbuffers::Verifier&, kmeans::Packet::<unnamed enum>) const’
  182 |            VerifyField<int32_t>(verifier, VT_DURATION) &&
      |                                                      ^

/snort_src/snort3_extra-master/src/inspectors/dpx/packet_generated.h:184:43: error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*)’
  184 |            verifier.Verify(protocol_type()) &&
      |                                           ^
In line 186 of plugin/packet_generated.h
error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*) verifier.Verify(service())

In line 188 of plugin/packet_generated.h
error: no matching function for call to ‘flatbuffers::Verifier::Verify(const flatbuffers::String*) verifier.Verify(flag())

/snort_src/snort3_extra-master/src/inspectors/dpx/packet_generated.h:189:55: error: no matching function for call to ‘kmeans::Packet::VerifyField<int32_t>(flatbuffers::Verifier&, kmeans::Packet::<unnamed enum>) const’
  189 |            VerifyField<int32_t>(verifier, VT_SRC_BYTES) &&
      |                                                       ^

/snort_src/snort3_extra-master/src/inspectors/dpx/packet_generated.h:190:55: error: no matching function for call to ‘kmeans::Packet::VerifyField<int32_t>(flatbuffers::Verifier&, kmeans::Packet::<unnamed enum>) const’
  190 |            VerifyField<int32_t>(verifier, VT_DST_BYTES) &&
      |                                                       ^

/snort_src/snort3_extra-master/src/inspectors/dpx/packet_generated.h:191:50: error: no matching function for call to ‘kmeans::Packet::VerifyField<int32_t>(flatbuffers::Verifier&, kmeans::Packet::<unnamed enum>) const’
  191 |            VerifyField<int32_t>(verifier, VT_LAND) &&
      |                                      

and all attributes, i already installed flatbuffers, what must i do then?
