### ISSUE TITLE
Plugin not capturing any packets

### ISSUE THREAD

**Issue by ahuseinnf** [benzi96/snort3-plugin-ML#6]
![image](https://user-images.githubusercontent.com/58802002/165256871-b60691c9-17e3-49cf-8103-5e19df184bb7.png)

my snort3 plugin machine learning not capturing any packets, i followed whole instruction, when i test it with hping3 no packet captured but the logs form original rules for icmp captured them

![image](https://user-images.githubusercontent.com/58802002/165257461-b8ac15d3-32d3-4c2e-8a98-b4268d34394b.png)

**Comment by benzi96** [comment]
![image](https://user-images.githubusercontent.com/32060434/166741635-0de443d5-4cfe-4df1-a2bd-040e061f6fb6.png)
 I tested and it's working fine.
Please turn off any other plugins of snort3 so it don't block the packets

**Comment by ahuseinnf** [comment]
> ![image](https://user-images.githubusercontent.com/32060434/166741635-0de443d5-4cfe-4df1-a2bd-040e061f6fb6.png) I tested and it's working fine. Please turn off any other plugins of snort3 so it doesn't block the packets

is it still working if i enabled logging for my snort? i wanna visualized my logs on elk too so i need to enabled my snort logging on snort.lua... or the snort3 service must keep going on the terminal?

**Comment by ahuseinnf** [comment]
i always got this backtrace error

Commencing packet processing
++ [0] enp0s3
Set GID to 997
Set UID to 997

Snort (PID 28151) caught fatal signal: SIGSEGV (11)
Version: 3.1.27.0

Backtrace:
  #0 0x7f1098b95320 in _ZN3Dpx7predictB5cxx11EPN16FeatureExtractor20ConversationFeaturesE+0x1380 (/usr/local/snort/lib/snort/plugins/extra/inspectors/dpx.so @0x7f1098b7f000)
  #1 0x7f1098b9771d in _ZN3Dpx4evalEPN5snort6PacketE+0xbd (/usr/local/snort/lib/snort/plugins/extra/inspectors/dpx.so @0x7f1098b7f000)
  #2 0x55a177497c45 in _ZN5snort16InspectorManager16internal_executeILb0EEEvPNS_6PacketE+0x165 (/usr/local/snort/bin/snort @0x55a1772d9000)
  #3 0x55a1773f15dc in _ZN5snort15DetectionEngine7inspectEPNS_6PacketE+0x6c (/usr/local/snort/bin/snort @0x55a1772d9000)
  #4 0x55a1774700e8 in _ZL14process_packetPN5snort6PacketE+0x88 (/usr/local/snort/bin/snort @0x55a1772d9000)
  #5 0x55a177470d0d in _ZN8Analyzer19process_daq_pkt_msgEPK8_daq_msgb+0xbd (/usr/local/snort/bin/snort @0x55a1772d9000)
  #6 0x55a177470f2f in _ZN8Analyzer15process_daq_msgEPK8_daq_msgb+0x1cf (/usr/local/snort/bin/snort @0x55a1772d9000)
  #7 0x55a177472173 in _ZN8Analyzer16process_messagesEv+0x113 (/usr/local/snort/bin/snort @0x55a1772d9000)
  #8 0x55a177472465 in _ZN8Analyzer7analyzeEv+0xa5 (/usr/local/snort/bin/snort @0x55a1772d9000)
  #9 0x55a1774725a5 in _ZN8AnalyzerclEP7Swappert+0xb5 (/usr/local/snort/bin/snort @0x55a1772d9000)
  #10 0x7f109d1fc6df in _ZNKSt10error_code23default_error_conditionEv+0x2f (/usr/lib/x86_64-linux-gnu/libstdc++.so.6 @0x7f109d13f000)
  #11 0x7f109ed9e6db in start_thread+0xdb (/lib/x86_64-linux-gnu/libpthread.so.0 @0x7f109ed97000)
  #12 0x7f109c8b061f in clone+0x3f (/lib/x86_64-linux-gnu/libc.so.6 @0x7f109c78f000)

= Current DAQ Message (Type 1) =

== Header (48) ==
9e6c 7862 0000 0000 e120 0400 0000 0000
5000 0000 ffff ffff ffff ffff ffff ffff
0000 0000 0000 0000 0000 0000 0000 0000

== Data (80) ==
0100 5e67 7f98 0800 27c4 0a85 0800 45c0
0042 b2d6 0000 0101 9516 0a00 020f e567
7f98 0303 6e2f 0000 0000 4500 0026 cc9f
0000 4011 3d19 e567 7f98 0a00 020f 3a97
1388 0012 86e2 5858 5858 5858 5858 5858

Segmentation fault (core dumped)

**Comment by ahuseinnf** [comment]
> ![image](https://user-images.githubusercontent.com/32060434/166741635-0de443d5-4cfe-4df1-a2bd-040e061f6fb6.png) I tested and it's working fine. Please turn off any other plugins of snort3 so it doesn't block the packets

![image](https://user-images.githubusercontent.com/58802002/167527995-3720138a-89a5-4303-9b85-37f2cfb8605d.png)

the plugin finally capturing the packets, but its not classified as DoS or etc, any suggest please?
