### ISSUE TITLE
can i know the accuracy？

### ISSUE THREAD

**Issue by songsir111** [benzi96/snort3-plugin-ML#8]
Can this project show the accuracy of the results? If so, what command can I run to see the accuracy?Looking forward to your reply.

**Comment by benzi96** [comment]
To calculate the accuracy:
- you will need to know the classification of incoming packet (normal or anomaly)
- the result when the machine learning algorithm predict the packet (normal or anomaly)

e.g:  you send 3 packets: first one is normal, second and third is anomaly

The machine learning algorithm predict:
 + first one is normal - correct
 + second one is normal - wrong
 + third one is anomaly - correct

=> accuracy: 2/3 = 66.6%

The machine learning algorithm predict:
 + first one is anomaly - wrong
 + second one is normal - wrong
 + third one is anomaly - correct

=> accuracy: 1/3 = 33.3%

The machine learning algorithm predict:
 + first one is normal - correct
 + second one is anomaly - correct
 + third one is anomaly - correct

=> accuracy: 3/3 = 100%

In real life scenario, when we receive the packets, we don't know the classification of incoming packet => we can't calculate the accuracy.

if you want to calculate the accuracy, you need to save the data to a file and classify the packets (normal or anomaly)

Please refer to https://github.com/benzi96/snort3-plugin-ML/blob/master/AnalysisServer/mainfile_analyze%20file%20data.py
This will save the packet features to a file, then you classify each packet to normal or anomaly. After that you can calculate accuracy using test_clf() function like this:

neutralNetwork.load_test_data(currentFileName)
data, acc = neutralNetwork.test_clf()

**Comment by songsir111** [comment]
Thank you very much for your reply! i will try it
